hordes:
  basicHorde:
    mob: "basic"
    amountMin: 30
    amountMax: 50
mobs:
  basic:
    type: SKELETON
    name: "&7&lBASIC HORDE MOB"
    items:
      mainHand: {}
      helmet: {}
      chestplate: {}
      leggings: {}
      boots: {}