hordes:
  basicHorde:
    mob: "basic"
    amountMin: 30
    amountMax: 50
mobs:
  basic:
    type: SKELETON
    name: "&7&lBASIC HORDE MOB"
    mainHand: { }
    helmet: { }
    chestplate: { }
    leggings: { }
    boots: { }
    drops:
locations: {}